name: Compressed Size

on: [pull_request]

jobs:
    compressed_size:
        name: Compressed Size
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.15'
            - uses: preactjs/compressed-size-action@v1
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  build-script: makeBuild
