name: Compressed Size

on: [pull_request]

jobs:
    compressed_size:
        name: Compressed Size
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '14.15'
            - uses: preactjs/compressed-size-action@v2
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  pattern: "**/build/**/*.js"

